<!DOCTYPE HTML>
<html>
<head>
<script src="MyPromise2.js"></script>
<script type="text/javascript">
	/*
	let getJSON = url => {
		return new MyPromise2((resolve, reject) => {
			let xhr = new XMLHttpRequest();
			xhr.open("GET", url);
			xhr.reponseType = "json";
			xhr.setRequestHeader("Accept", "application/json");
			xhr.send(null);
			
			xhr.onreadystatechange = () => {
				//if (this.readyState !== 4) return;
				//if (this.status === 200) {
					resolve(this.response);
				//} else {
				//	reject(new Error("failed: " + this.statusText));
				//}
			};
		});
	}
	getJSON("test.json").then(json => {
		console.log(`Contents: ${json}`);
	}).catch(error => {
		console.log(`Error: ${error}`);
	});
	*/
	
	/*
	let p1 = new Promise((resolve, reject) => {
		resolve("OK");
	});

	let p2 = new Promise((resolve, reject) => {
		resolve(p1);
	});

	p2.then(value => console.log(value)).finally(function() {
		console.log("finally");
	}).then(() => console.log("xxx"));
	*/
	/*
	let p1 = new MyPromise2((resolve, reject) => {
		resolve("OK");
	});

	let p2 = new MyPromise2((resolve, reject) => {
		reject(p1);
	});

	p2.then(value => console.log(value)).finally(function() {
		console.log("finally");
	}).then(() => console.log("xxx")).catch(error => console.log("error: " + error));
	*/
	
	/*
	let promise = new MyPromise2((resolve, reject) => {
		console.log("Promise");
		resolve();
	});
	
	promise.then(() => {
		console.log("Resolved.");
	});
	console.log("Hi!");
	
	let p1 = new MyPromise2((resolve, reject) => {
		setTimeout(() => reject(new Error("fail")), 3000);
	});
	
	let p2 = new MyPromise2((resolve, reject) => {
		setTimeout(() => resolve(p1), 1000);
	});
	
	p2.then(result => console.log(result)).catch(error => console.log(error));
	
	new MyPromise2((resolve, reject) => {
		resolve(1);
		console.log(2);
	}).then(r => console.log(r));
	
	let promise = new MyPromise2((resolve, reject) => {
		throw new Error("test");
	});
	
	promise.catch(error => {
		console.log(error);
	});
	
	let promise = new MyPromise2((resolve, reject) => {
		try {
			throw new Error("test");
		} catch(e) {
			reject(e);
		}
	});
	
	promise.catch(error => {
		console.log(error);
	});
	
	promise = new MyPromise2((resolve, reject) => {
		reject(new Error("test"));
	});
	
	promise.catch(error => {
		console.log(error);
	});
	
	promise = new MyPromise2((resolve, reject) => {
		resolve("ok");
		throw new Error("test");
	});
	
	promise.then(value => {
		console.log(value);
	}).catch(error => {
		console.log(error);
	});
	
	let someAsyncThing = () => {
		return new MyPromise2((resolve, reject) => {
			resolve(x + 2);
		});
	};
	
	someAsyncThing().then(() => {
		console.log("everything is great");
	});
	
	let promise = new MyPromise2((resolve, reject) => {
		resolve("ok");
		setTimeout(() => {
			throw new Error("test");
		}, 0);
	});
	
	promise.then((value) => {
		console.log(value);
	});
	
	let someAsyncThing = () => {
		return new MyPromise2((resolve, reject) => {
			resolve(x + 2);
		});
	};
	someAsyncThing().catch((error) => {
		console.log("oh no", error);
	}).then(() => {
		console.log("carry on");
	});
	
	MyPromise2.resolve().catch((error) => {
		console.log(error);
	}).then(() => {
		console.log("carry on");
	});
	
	let someAsyncThing = () => {
		return new MyPromise2((resolve, reject) => {
			resolve(x + 2);
		});
	};
	
	someAsyncThing().then(() => someOtherAsyncThing()).catch(error => {
		console.log("oh no", error);
		y + 2;
	}).then(() => {
		console.log("carry on");
	}).catch(error => {
		console.log("carry on", error);
	});
	
	const p1 = new MyPromise2((resolve, reject) => {
		resolve("hello");
	}).then(result => result).catch(e => e);
	
	const p2 = new MyPromise2((resolve, reject) => {
		throw new Error("failed");
	}).then(result => result).catch(e => {throw e;});
	
	MyPromise2.all([p1, p2]).then(result => console.log("success: " + result)).catch(e => console.log("Error: " + e));
	
	const p1 = new MyPromise2((resolve, reject) => {
		resolve("hello");
	}).then(result => result);
	
	const p2 = new MyPromise2((resolve, reject) => {
		throw new Error("failed");
	}).then(result => result);
	
	MyPromise2.all([p1, p2]).then(result => console.log("success: " + result)).catch(e => console.log("Error: " + e));
	
	const p1 = new MyPromise2((resolve, reject) => {
		setTimeout(() => {
			resolve("hello");
		}, 10);
	}).then(result => result);
	
	const p2 = new MyPromise2((resolve, reject) => {
		setTimeout(() => {
			resolve("world");
		}, 11);
	}).then(result => result);
	
	MyPromise2.race([p1, p2]).then(result => console.log("success: " + result)).catch(e => console.log("Error: " + e));
	
	let p1 = new MyPromise2((resolve, reject) => {
		resolve("OK");
	});

	let p2 = new MyPromise2((resolve, reject) => {
		resolve(p1);
	});

	let p3 = new MyPromise2((resolve, reject) => {
		resolve(p2);
	});

	p3.then(value => console.log(value)).finally(function() {
		console.log("finally");
	}).then(() => console.log("xxx"));
	*/
	
	
</script>
</head>
<body>
</body>
</html>
